[project]
name = "osis-kjv-apocrypha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "httpx==0.28.1",
    "playwright>=1.54.0",
    "playwright-stealth>=2.0.0",
    "pyosis==0.2.1",
]
